// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZjXJ5QT4m1eoAU6zcxdM6vI9lr5TNQJc',
    appId: '1:1009821210872:web:2619f66b7bb2f9a83c030d',
    messagingSenderId: '1009821210872',
    projectId: 'chatapp001-b2519',
    authDomain: 'chatapp001-b2519.firebaseapp.com',
    storageBucket: 'chatapp001-b2519.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZy2R6963NETCkOq15ONRK-93tpkWy-ZM',
    appId: '1:1009821210872:android:a80682745d993d963c030d',
    messagingSenderId: '1009821210872',
    projectId: 'chatapp001-b2519',
    storageBucket: 'chatapp001-b2519.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKYioufmh1MvSdPj3pb4p9f7dAFG27ujY',
    appId: '1:1009821210872:ios:f3dba7eaa4a18e7b3c030d',
    messagingSenderId: '1009821210872',
    projectId: 'chatapp001-b2519',
    storageBucket: 'chatapp001-b2519.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
}
